### ISSUE TITLE
Failed to activate the scope-inspector package

### ISSUE THREAD

**Issue by Leonie-** [tvooo/scope-inspector#18]
When attempting to install the package using the GUI, I get the error "Failed to activate the scope-inspector package - Cannot read property 'getHoistedIdentifiers' of null"

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.5
**Thrown From**: [scope-inspector](https://github.com/tvooo/scope-inspector) package, v0.2.1

### Stack Trace
Failed to activate the scope-inspector package

```
At Cannot read property 'getHoistedIdentifiers' of null

TypeError: Cannot read property 'getHoistedIdentifiers' of null
  at Inspection.module.exports.Inspection.updateHoistingIndicators (/Users/kenyol04/.atom/packages/scope-inspector/lib/inspection.coffee:103:31)
  at /Users/kenyol04/.atom/packages/scope-inspector/lib/inspection.coffee:43:8
  at Config.module.exports.Config.observeKeyPath (/Users/kenyol04/Downloads/Atom.app/Contents/Resources/app/src/config.js:621:7)
  at Config.module.exports.Config.observe (/Users/kenyol04/Downloads/Atom.app/Contents/Resources/app/src/config.js:133:21)
  at Inspection.module.exports.Inspection.registerEvents (/Users/kenyol04/.atom/packages/scope-inspector/lib/inspection.coffee:42:17)
  at new Inspection (/Users/kenyol04/.atom/packages/scope-inspector/lib/inspection.coffee:27:6)
  at ScopeInspector.updateInspection (/Users/kenyol04/.atom/packages/scope-inspector/lib/scope-inspector.coffee:24:22)
  at /Users/kenyol04/.atom/packages/scope-inspector/lib/scope-inspector.coffee:17:8
  at WorkspaceView.module.exports.WorkspaceView.eachEditorView (/Users/kenyol04/Downloads/Atom.app/Contents/Resources/app/src/workspace-view.js:92:9)
  at ScopeInspector.registerInspections (/Users/kenyol04/.atom/packages/scope-inspector/lib/scope-inspector.coffee:13:24)
  at ScopeInspector.activate (/Users/kenyol04/.atom/packages/scope-inspector/lib/scope-inspector.coffee:43:26)
  at Package.module.exports.Package.activateNow (/Users/kenyol04/Downloads/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Users/kenyol04/Downloads/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Users/kenyol04/Downloads/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Users/kenyol04/Downloads/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Users/kenyol04/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Users/kenyol04/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Users/kenyol04/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Users/kenyol04/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Users/kenyol04/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Users/kenyol04/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -8:32.0 core:move-down (atom-text-editor.editor)
     -8:31.7 core:backspace (atom-text-editor.editor)
     -8:31.2 core:move-up (atom-text-editor.editor)
     -8:30.8 snippets:next-tab-stop (atom-text-editor.editor)
     -8:30.8 snippets:expand (atom-text-editor.editor)
     -8:30.8 editor:indent (atom-text-editor.editor)
  4x -8:23.5 core:move-left (atom-text-editor.editor)
     -6:42.4 core:delete (atom-text-editor.editor.mini)
     -6:37.0 core:confirm (atom-text-editor.editor.mini)
     -5:45.3 find-and-replace:select-all (atom-text-editor.editor)
     -5:44.6 core:move-right (atom-text-editor.editor)
  3x -5:42.7 core:backspace (atom-text-editor.editor)
 60x -5:41.0 core:undo (atom-text-editor.editor)
     -1:48.4 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor)
     -0:41.3 core:delete (atom-text-editor.editor.mini)
     -0:37.3 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
js-refactor, v0.3.0
jshint, v1.3.0
react, v0.10.1
refactor, v0.4.1
scope-inspector, v0.2.1

# Dev
No dev packages
```

**Comment by tvooo** [comment]
Hi @Leonie- 
This should be fixed with the latest update and 0586fa52042efda1aef0f0d795a071bd6ca4581e. Can you verify that it doesn't occur anymore?

Thanks, Tim

**Comment by Leonie-** [comment]
@tvooo - Yes, all fine now, thanks!

**Comment by zrhmn** [comment]
Nope. Still going strong.

**Atom Version:** 0.200.0
**System:** Linux (Ubuntu 14.04.2)
**Thrown From:** scope-inspector package, v1.0.1

(I don't know how to do the other fancy stuff. So instead a screenshot is provided which linked me to this issue directly. This wasn't happening until the recent packages upgrade. Should I create a new issue?)

![screenshot](https://dl.dropboxusercontent.com/1/view/m2ctohambfvb04v/Apps/Shutter/20150525185735-1addf0df.png)

**Comment by KamilKowalczyk** [comment]
I've the same problem with scope-inspector in latest version of Atom (0.210.0). :/

**Comment by rodocite** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.4
**Thrown From**: [scope-inspector](https://github.com/tvooo/scope-inspector) package, v1.0.1

### Stack Trace

Failed to activate the scope-inspector package

```
At Cannot read property 'getHoistedIdentifiers' of null

TypeError: Cannot read property 'getHoistedIdentifiers' of null
  at Inspection.module.exports.Inspection.updateHoistingIndicators (/Users/rodo/.atom/packages/scope-inspector/lib/inspection.coffee:101:31)
  at /Users/rodo/.atom/packages/scope-inspector/lib/inspection.coffee:41:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
  at Inspection.module.exports.Inspection.registerEvents (/Users/rodo/.atom/packages/scope-inspector/lib/inspection.coffee:40:17)
  at new Inspection (/Users/rodo/.atom/packages/scope-inspector/lib/inspection.coffee:25:6)
  at ScopeInspector.updateInspection (/Users/rodo/.atom/packages/scope-inspector/lib/scope-inspector.coffee:23:22)
  at /Users/rodo/.atom/packages/scope-inspector/lib/scope-inspector.coffee:17:8
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:276:9)
  at ScopeInspector.registerInspections (/Users/rodo/.atom/packages/scope-inspector/lib/scope-inspector.coffee:13:20)
  at ScopeInspector.activate (/Users/rodo/.atom/packages/scope-inspector/lib/scope-inspector.coffee:60:26)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:469:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:324:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:464:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:670:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.require.extensions.(anonymous function) [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:166:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:82:25)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "scope-inspector": {}
}
```

### Installed Packages

``` coffee
# User
emmet, v2.3.12
highlight-selected, v0.10.1
linter, v1.5.0
linter-eslint, v3.0.2
react, v0.12.6
scope-inspector, v1.0.1
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

Still getting errors.

**Comment by ansi6622** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [scope-inspector](https://github.com/tvooo/scope-inspector) package, v1.0.1

### Stack Trace

Failed to activate the scope-inspector package

```
At Cannot read property 'getHoistedIdentifiers' of null

TypeError: Cannot read property 'getHoistedIdentifiers' of null
    at Inspection.module.exports.Inspection.updateHoistingIndicators (/Users/AnthonyTron/.atom/packages/scope-inspector/lib/inspection.coffee:101:31)
    at /Users/AnthonyTron/.atom/packages/scope-inspector/lib/inspection.coffee:41:8
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:141:21)
    at Inspection.module.exports.Inspection.registerEvents (/Users/AnthonyTron/.atom/packages/scope-inspector/lib/inspection.coffee:40:17)
    at new Inspection (/Users/AnthonyTron/.atom/packages/scope-inspector/lib/inspection.coffee:25:6)
    at ScopeInspector.updateInspection (/Users/AnthonyTron/.atom/packages/scope-inspector/lib/scope-inspector.coffee:23:22)
    at /Users/AnthonyTron/.atom/packages/scope-inspector/lib/scope-inspector.coffee:17:8
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:290:9)
    at ScopeInspector.registerInspections (/Users/AnthonyTron/.atom/packages/scope-inspector/lib/scope-inspector.coffee:13:20)
    at ScopeInspector.activate (/Users/AnthonyTron/.atom/packages/scope-inspector/lib/scope-inspector.coffee:60:26)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ]
  },
  "scope-inspector": {
    "userId": "d52f8a8b7cae8ad76983fc9a6777a7d58863332e"
  }
}
```

### Installed Packages

``` coffee
# User
atom-material-ui, v0.8.1
browser-plus, v0.0.54
browser-refresh, v0.9.0
color-picker, v2.1.1
color-tabs, v0.1.8
colorful-cursor, v0.3.1
colorful-json, v1.0.0
ctags-status, v1.3.4
emmet, v2.4.1
file-icons, v1.6.14
glowing-cursor, v0.1.1
highlight-selected, v0.11.2
linter, v1.11.3
minimap, v4.19.0
minimap-pigments, v0.1.7
open-recent, v5.0.0
pigments, v0.23.1
rainbow-tabs, v2.2.1
scope-inspector, v1.0.1
swackets, v0.10.0

# Dev
No dev packages
```

**Comment by sylann** [comment]
# Stack Trace

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.8
**System**: Ubuntu 16.04.1
**Thrown From**: [scope-inspector](https://github.com/tvooo/scope-inspector) package, v1.0.1

### Stack Trace

Failed to activate the scope-inspector package

```
At Cannot read property 'getHoistedIdentifiers' of null

TypeError: Cannot read property 'getHoistedIdentifiers' of null
    at Inspection.module.exports.Inspection.updateHoistingIndicators (/home/rom/.atom/packages/scope-inspector/lib/inspection.coffee:101:31)
    at /home/rom/.atom/packages/scope-inspector/lib/inspection.coffee:41:8
    at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app.asar/src/config.js:612:7)
    at Config.module.exports.Config.observe (/usr/share/atom/resources/app.asar/src/config.js:141:21)
    at Inspection.module.exports.Inspection.registerEvents (/home/rom/.atom/packages/scope-inspector/lib/inspection.coffee:40:17)
    at new Inspection (/home/rom/.atom/packages/scope-inspector/lib/inspection.coffee:25:6)
    at ScopeInspector.updateInspection (/home/rom/.atom/packages/scope-inspector/lib/scope-inspector.coffee:23:22)
    at /home/rom/.atom/packages/scope-inspector/lib/scope-inspector.coffee:17:8
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:330:9)
    at ScopeInspector.registerInspections (/home/rom/.atom/packages/scope-inspector/lib/scope-inspector.coffee:13:20)
    at ScopeInspector.activate (/home/rom/.atom/packages/scope-inspector/lib/scope-inspector.coffee:60:26)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:342:19
    at /usr/share/atom/resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/usr/share/atom/resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:169:14)
    at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:324:27)
    at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "frameworks",
      "node_modules"
    ],
    "themes": [
      "one-dark-ui",
      "dracula-theme"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
adventurous-syntax, v0.2.0 (inactive)
atom-alignment, v0.12.1 (active)
atom-bootstrap3, v1.2.12 (inactive)
color-picker, v2.2.2 (active)
dracula-theme, v1.2.8 (active)
file-icons, v1.7.18 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
indent-guide-improved, v1.4.9 (active)
javascript-snippets, v1.2.1 (active)
linter, v1.11.16 (active)
linter-jshint, v2.1.0 (active)
minimap, v4.24.7 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-highlight-selected, v4.4.0 (active)
monokai, v0.18.0 (inactive)
pigments, v0.31.2 (active)
polymorph-ui, v1.8.8 (inactive)
scope-inspector, v1.0.1 (inactive)
sequential-number, v0.4.0 (inactive)
split-diff, v1.0.4 (inactive)
symbols-tree-view, v0.13.2 (active)
transform, v0.4.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by a7madgamal** [comment]
[Enter steps to reproduce below:]
1. enable package from the packages tab

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [scope-inspector](https://github.com/tvooo/scope-inspector) package, v1.0.1

### Stack Trace

Failed to activate the scope-inspector package

```
At Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at Object.content (/Users/mido/.atom/packages/scope-inspector/lib/scope-view-single.coffee:8:79)
    at Builder.tag (/Users/mido/.atom/packages/scope-inspector/node_modules/space-pen/lib/space-pen.js:281:19)
    at Function.View.(anonymous function) [as div] (/Users/mido/.atom/packages/scope-inspector/node_modules/space-pen/lib/space-pen.js:83:49)
    at Function.module.exports.ScopeView.content (/Users/mido/.atom/packages/scope-inspector/lib/scope-view-single.coffee:6:6)
    at Function.<anonymous> (/Users/mido/.atom/packages/scope-inspector/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/Users/mido/.atom/packages/scope-inspector/node_modules/space-pen/lib/space-pen.js:123:10)
    at ScopeView.View [as constructor] (/Users/mido/.atom/packages/scope-inspector/node_modules/space-pen/lib/space-pen.js:155:33)
    at new ScopeView (/Users/mido/.atom/packages/scope-inspector/lib/scope-view-single.coffee:5:3)
    at ScopeInspectorView.module.exports.ScopeInspectorView.renderScope (/Users/mido/.atom/packages/scope-inspector/lib/scope-inspector-view.coffee:61:27)
    at Inspection.module.exports.Inspection.onCursorMoved (/Users/mido/.atom/packages/scope-inspector/lib/inspection.coffee:86:33)
    at Inspection.module.exports.Inspection.onSaved (/Users/mido/.atom/packages/scope-inspector/lib/inspection.coffee:138:6)
    at new Inspection (/Users/mido/.atom/packages/scope-inspector/lib/inspection.coffee:24:6)
    at ScopeInspector.updateInspection (/Users/mido/.atom/packages/scope-inspector/lib/scope-inspector.coffee:23:22)
    at /Users/mido/.atom/packages/scope-inspector/lib/scope-inspector.coffee:17:8
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:332:9)
    at ScopeInspector.registerInspections (/Users/mido/.atom/packages/scope-inspector/lib/scope-inspector.coffee:13:20)
    at ScopeInspector.activate (/Users/mido/.atom/packages/scope-inspector/lib/scope-inspector.coffee:60:26)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:342:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:827:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:169:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:343:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -9:09.7.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -9:09.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -9:09.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -9:06.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active.hyperclick)
  2x -8:20.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:09.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:31.1.0 core:copy (atom-text-editor.editor.is-focused.hyperclick)
     -1:29.2.0 core:paste (atom-text-editor.editor.is-focused.hyperclick)
     -1:20.5.0 core:copy (atom-text-editor.editor.is-focused.hyperclick)
     -1:18 core:paste (atom-text-editor.editor.is-focused.hyperclick)
     -1:15.9.0 core:delete (atom-text-editor.editor.is-focused)
     -0:49 command-palette:toggle (atom-text-editor.editor.is-focused.hyperclick)
  7x -0:40.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:30.6.0 editor:log-cursor-scope (atom-text-editor.editor.hyperclick)
     -0:13.4.0 settings-view:open (atom-text-editor.editor.is-focused.hyperclick)
     -0:13.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-gruvbox-plus-syntax.theme-slim-dark-ui.editor-background.find-visible)
```

### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "highlight-column",
      "linter-js-standard",
      "grammar-tab-colors",
      "minimap-autohide",
      "autohide-tree-view",
      "multirow-tabs",
      "tree-view-git-status",
      "chary-tree-view",
      "language-dotenv",
      "method-separator",
      "minimap-codeglance",
      "minimap-split-diff",
      "source-preview-pug",
      "useful-context-menu",
      "atom-pair",
      "source-preview",
      "tab-smart-sort",
      "git-status",
      "ctrl-last-tab",
      "jshint",
      "atom-easy-jsdoc",
      "npm-docs"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/mido/projects",
    "themes": [
      "slim-dark-ui",
      "gruvbox-plus-syntax"
    ]
  },
  "scope-inspector": {
    "trackUsageMetrics": false,
    "userId": "43315c604e99ba26febae2cd5e2176922f021b31"
  }
}
```

### Installed Packages

``` coffee
# User
activate-power-mode, v0.9.0 (active)
atom-beautify, v0.29.13 (active)
atom-chai-snippets, v0.3.0 (active)
atom-easy-jsdoc, v4.7.1 (inactive)
atom-jade, v0.3.0 (active)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-package-manager, v1.9.3 (active)
atom-pair, v2.0.10 (inactive)
atom-ternjs, v0.15.0 (active)
auto-update-packages, v1.0.1 (active)
autoclose-html, v0.23.0 (active)
autocomplete-html-entities, v0.1.0 (active)
autocomplete-json, v5.1.0 (active)
autocomplete-modules, v1.6.3 (active)
autocomplete-paths, v1.0.2 (active)
autocomplete-ruby, v0.1.0 (active)
autohide-tree-view, v0.25.1 (inactive)
chary-tree-view, v0.2.3 (inactive)
clear-syntax, v0.6.0 (inactive)
coral-blue-syntax, v0.2.0 (inactive)
ctrl-last-tab, v0.3.0 (inactive)
dark-flat-ui, v1.2.4 (inactive)
docblockr, v0.8.5 (active)
dracula-theme, v1.2.8 (inactive)
editor-background, v1.2.23 (active)
editor-stats, v0.17.0 (active)
editorconfig, v1.4.1 (active)
file-icons, v1.7.19 (active)
file-types, v0.5.4-p1 (active)
flatwhite-syntax, v0.7.1 (inactive)
fonts, v1.6.0 (active)
git-blame, v0.4.11 (inactive)
git-diff-details, v1.3.0 (active)
git-projects, v1.17.0 (inactive)
git-status, v0.3.4 (inactive)
git-time-machine, v1.5.3 (inactive)
goto-last-edit, v0.3.2 (active)
gruvbox-plus-syntax, v1.2.5 (active)
highlight-column, v0.5.1 (inactive)
highlight-selected, v0.11.2 (active)
hyperclick, v0.0.38 (active)
incremental-search, v5.1.0 (inactive)
js-hyperclick, v1.6.0 (active)
jshint, v1.8.6 (inactive)
language-dots, v0.0.4 (active)
language-pug, v0.0.18 (active)
last-cursor-position, v0.9.0 (active)
linter, v1.11.16 (active)
linter-coffeelint, v1.1.2 (active)
linter-jshint, v2.1.0 (active)
linter-pug-lint, v0.2.0 (active)
method-separator, v0.1.4 (inactive)
minimap, v4.25.0 (active)
minimap-autohide, v0.10.1 (inactive)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
monokai, v0.18.0 (inactive)
npm-docs, v0.2.0 (inactive)
open-in-browser, v0.4.7 (active)
open-recent, v5.0.0 (active)
outlander-syntax, v1.1.0 (inactive)
package-cop, v0.2.10 (active)
package-list, v0.1.2 (inactive)
package-sync, v1.1.0 (active)
package-sync-plus, v0.1.2 (inactive)
path-hyperclick, v0.3.0 (active)
pigments, v0.35.1 (active)
polaris-syntax, v0.1.0 (inactive)
pretty-json, v1.6.0 (active)
project-manager, v3.2.3 (active)
robin-hood-syntax, v1.0.0 (inactive)
scope-inspector, v1.0.1 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
simple-drag-drop-text, v0.3.1 (active)
slim-dark-ui, v0.12.0 (active)
source-preview, v0.5.0 (inactive)
source-preview-pug, v0.2.0 (inactive)
split-diff, v1.0.4 (inactive)
synced-sidebar, v0.4.3 (active)
tab-smart-sort, v0.1.4 (inactive)
terminal-plus, v0.14.5 (active)
tool-bar, v1.0.1 (active)
tool-bar-main, v0.0.10 (active)
twilight-syntax, v0.7.0 (inactive)
useful-context-menu, v0.6.0 (inactive)
vertical-tabs, v0.4.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by DanMan** [comment]
So, project abandoned? Still getting the error in Atom 1.26.1

**Comment by tvooo** [comment]
Pretty much. This was written back when Atom was all CoffeeScript, and it doesn't even know about ES6 block scope (like what `const` and `let` create). As I'm not using it myself, it's not been on my priority list to work on. Do you think this would still be useful for you? If people made an argument for the project's usefulness, I'd consider picking it up again.

**Comment by DanMan** [comment]
Well, I'm used to something like this from Phpstorm, so it'd be nice to have but not all that urgent, if you have better things to do. :)
